config/routes.rb
Rails.application.routes.draw do

  resources :codes

  root "codes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :codes
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  before_action :find_code, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @codes = Code.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @codes = Code.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def new
     @code = Code.new
  end

  def create
     @code = Code.new code_params
     if @code.save
       redirect_to codes_path
     else
       render :new
     end
  end

  def show
  end

  def edit
  end

  def update
     if @code.update code_params
       redirect_to @code
     else
       render :edit
     end
  end


  def destroy
     @code.destroy
     redirect_to root_path
  end


  private

  def find_code
     @code = Code.find params[:id]
  end

  def code_params
     params.require(:code).permit(:kind, :title, :work, :category_id)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<div class="container">
  <% if @code.errors.any? %>
    <h2><%= pluralize(@code.errors.count, "error") %> prevent this code
        from saving</h2>
    <ul>
      <% @code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for @code do |f| %>
  <div class="form-group">
    <%= f.label :kind %><br>
      <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %><br>
  </div>
  <div class="form-group">
    <%= f.label :work %><br>
    <%= f.text_area :work, class: "form-control" %><br>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "form-control" %>
  </div>
  <% end %>
</div>

app/views/codes/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit your snippet</h1>
 <%= render "form" %>
</div>

app/views/codes/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-8">
      <% @codes.each do |code| %>
        <h1><%= link_to code.category.name, code_path(code)%></h1>
        <hr>
      <% end %>
    </div>
    <div class="col-md-4"><br>
      <ul class="list-group">
        <li class="list-group-item"><%= link_to "All Categories", root_path %></li>
        <% Category.all.each do |category| %>
          <li class="list-group-item"><%= link_to category.name, codes_path(category: category.name) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/codes/new.html.erb
<div class="container">
  <h1 class="text-center">Create New Snippet</h1>

<%= render "form" %>
</div>

app/views/codes/show.html.erb
<div class="container"><br><br>
  <div class="well">
    <div class="row">
     <div class="col-md-4">
        <h1><%= @code.category.name %></h1><hr>
        <h3><%= @code.title %></h3><hr>
        <p>Submitted <%= time_ago_in_words(@code.created_at) %> Ago</p>
      </div>
      <div class="col-md-8">
        <blockquote class="blockquote">
          <h3><%= @code.work %></h3>
        </blockquote>
      </div>
    </div>
  </div>
  <div class="btn-group">
    <%= link_to "Edit", edit_code_path(@code), class: "btn btn-default" %>
    <%= link_to "Delete", code_path(@code), method: :delete,
                                                    data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
    <%= link_to "Home", root_path, class: "btn btn-default" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeSnippets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Play' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <%= link_to "Code Snippets", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Create New Snippet", new_code_path %></li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>